


ALTER TABLE INTEGRACION.TS_ASNT
 ADD (ASNT_ALMA_CODI  NUMBER);


COMMENT ON COLUMN INTEGRACION.TS_ASNT.ASNT_ALMA_CODI IS 'Numero de Almacen en NewStock';




ALTER TABLE INTEGRACION.TS_ASNT
 ADD (ASNT_HOTE_CODI  VARCHAR2(3));


COMMENT ON COLUMN INTEGRACION.TS_ASNT.ASNT_HOTE_CODI IS 'Follon Multihotel en una Licencia Hoteles Lopez';




UPDATE TH_PARA SET PARA_FECHA_BASE = '14-MAY-2010';
UPDATE TH_PARA SET PARA_FECHA_EXE  = '14-MAY-2010';

COMMIT;