



ALTER TABLE INTEGRACION.TH_HOTEL
 ADD (HOTEL_EMP_NUM  NUMBER                         DEFAULT 0                     NOT NULL);


COMMENT ON COLUMN INTEGRACION.TH_HOTEL.HOTEL_EMP_NUM IS 'Key Para Hoteles con mas de un Hotel en una sola empresa';


--

ALTER TABLE TH_HOTEL DROP CONSTRAINT TH_HOTEL_PK;
DROP INDEX TH_HOTEL_PK;


ALTER TABLE INTEGRACION.TH_HOTEL ADD 
CONSTRAINT TH_HOTEL_PK
 PRIMARY KEY (HOTEL_EMPGRUPO_COD, HOTEL_EMP_COD, HOTEL_EMP_NUM)

 ENABLE
 VALIDATE;
 

--


ALTER TABLE INTEGRACION.TH_PARA
 ADD (PARA_EMP_NUM  NUMBER                          DEFAULT 0);


COMMENT ON COLUMN INTEGRACION.TH_PARA.PARA_EMP_NUM IS 'Key Para Hoteles con mas de un Hotel en una sola empresa';


ALTER TABLE TH_PARA DROP CONSTRAINT TH_PARA_PK;
DROP INDEX TH_PARA_PK;



ALTER TABLE INTEGRACION.TH_PARA ADD 
CONSTRAINT TH_PARA_PK
 PRIMARY KEY (PARA_EMPGRUPO_COD, PARA_EMP_COD, PARA_EMP_NUM)

 ENABLE
 VALIDATE;




ALTER TABLE INTEGRACION.TH_HOTEL ADD 
CONSTRAINT TH_HOTEL_UN1
 UNIQUE (HOTEL_DESCRIPCION)

 ENABLE
 VALIDATE;


ALTER TABLE INTEGRACION.TH_PARA
 ADD (PARA_CTA_56DIGITO  VARCHAR2(15));


COMMENT ON COLUMN INTEGRACION.TH_PARA.PARA_CTA_56DIGITO IS 'Para Componer 5 y 6 digito cuenta de Clientes h.lopez';


--


ALTER TABLE INTEGRACION.TH_ASNT
 ADD (ASNT_EMP_NUM  NUMBER                          DEFAULT 0);


COMMENT ON COLUMN INTEGRACION.TH_ASNT.ASNT_EMP_NUM IS 'Key Para Hoteles con mas de un Hotel en una sola empresa';




ALTER TABLE TH_ASNT DROP CONSTRAINT TH_ASNT_PK;
DROP INDEX TH_ASNT_PK;



ALTER TABLE TH_ASNT ADD (
  CONSTRAINT TH_ASNT_PK
 PRIMARY KEY
 (ASNT_TIPO_REGISTRO, ASNT_EMPGRUPO_COD, ASNT_EMP_COD, ASNT_CFATOCAB_REFER, ASNT_LINEA, ASNT_F_VALOR,ASNT_EMP_NUM));




UPDATE TH_PARA SET PARA_FECHA_BASE = '10-FEB-2010';
UPDATE TH_PARA SET PARA_FECHA_EXE  = '10-FEB-2010';

COMMIT;