



ALTER TABLE TS_PARA
 ADD (PARA_DEBE_ABONO  VARCHAR2(4)                  DEFAULT 'D400');

ALTER TABLE TS_PARA
 ADD (PARA_HABER_ABONO  VARCHAR2(4)                 DEFAULT 'H400');


COMMENT ON COLUMN TS_PARA.PARA_DEBE_ABONO IS 'Indicador Facturas de Abono';

COMMENT ON COLUMN TS_PARA.PARA_HABER_ABONO IS 'Indicador Facturas de Abono';




UPDATE TH_PARA SET PARA_PAT_NUM = 'PAT0040';
UPDATE TH_PARA SET PARA_FECHA_BASE = '01-APR-2013';
UPDATE TH_PARA SET PARA_FECHA_EXE  = '01-APR-2013';

COMMIT;