


ALTER TABLE TH_ASNT
MODIFY(ASNT_AMPCPTO VARCHAR2(150 BYTE));





UPDATE TH_PARA SET PARA_PAT_NUM = 'PAT0040';
UPDATE TH_PARA SET PARA_FECHA_BASE = '02-FEB-2012';
UPDATE TH_PARA SET PARA_FECHA_EXE  = '02-FEB-2012';

COMMIT;