'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WebReferenceClientesNewHotel
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Clientes_Binding", [Namespace]:="urn:microsoft-dynamics-schemas/page/clientes")>  _
    Partial Public Class Clientes_Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ReadOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReadByRecIdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReadMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private IsUpdatedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetRecIdFromKeyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.HTitoNewHotelEnviar.My.MySettings.Default.HTitoNewHotelEnviar_WebReferenceClientesNewHotel_Clientes_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ReadCompleted As ReadCompletedEventHandler
        
        '''<remarks/>
        Public Event ReadByRecIdCompleted As ReadByRecIdCompletedEventHandler
        
        '''<remarks/>
        Public Event ReadMultipleCompleted As ReadMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event IsUpdatedCompleted As IsUpdatedCompletedEventHandler
        
        '''<remarks/>
        Public Event GetRecIdFromKeyCompleted As GetRecIdFromKeyCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateCompleted As CreateCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateMultipleCompleted As CreateMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCompleted As UpdateCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateMultipleCompleted As UpdateMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteCompleted As DeleteCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/clientes:Read", RequestNamespace:="urn:microsoft-dynamics-schemas/page/clientes", ResponseElementName:="Read_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/clientes", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Read(ByVal No As String) As <System.Xml.Serialization.XmlElementAttribute("Clientes")> Clientes
            Dim results() As Object = Me.Invoke("Read", New Object() {No})
            Return CType(results(0),Clientes)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadAsync(ByVal No As String)
            Me.ReadAsync(No, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadAsync(ByVal No As String, ByVal userState As Object)
            If (Me.ReadOperationCompleted Is Nothing) Then
                Me.ReadOperationCompleted = AddressOf Me.OnReadOperationCompleted
            End If
            Me.InvokeAsync("Read", New Object() {No}, Me.ReadOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadCompleted(Me, New ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/clientes:ReadByRecId", RequestNamespace:="urn:microsoft-dynamics-schemas/page/clientes", ResponseElementName:="ReadByRecId_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/clientes", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadByRecId(ByVal recId As String) As <System.Xml.Serialization.XmlElementAttribute("Clientes")> Clientes
            Dim results() As Object = Me.Invoke("ReadByRecId", New Object() {recId})
            Return CType(results(0),Clientes)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadByRecIdAsync(ByVal recId As String)
            Me.ReadByRecIdAsync(recId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadByRecIdAsync(ByVal recId As String, ByVal userState As Object)
            If (Me.ReadByRecIdOperationCompleted Is Nothing) Then
                Me.ReadByRecIdOperationCompleted = AddressOf Me.OnReadByRecIdOperationCompleted
            End If
            Me.InvokeAsync("ReadByRecId", New Object() {recId}, Me.ReadByRecIdOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadByRecIdOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadByRecIdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadByRecIdCompleted(Me, New ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/clientes:ReadMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/clientes", ResponseElementName:="ReadMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/clientes", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadMultiple(<System.Xml.Serialization.XmlElementAttribute("filter")> ByVal filter() As Clientes_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer) As <System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result"), System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> Clientes()
            Dim results() As Object = Me.Invoke("ReadMultiple", New Object() {filter, bookmarkKey, setSize})
            Return CType(results(0),Clientes())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadMultipleAsync(ByVal filter() As Clientes_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer)
            Me.ReadMultipleAsync(filter, bookmarkKey, setSize, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadMultipleAsync(ByVal filter() As Clientes_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer, ByVal userState As Object)
            If (Me.ReadMultipleOperationCompleted Is Nothing) Then
                Me.ReadMultipleOperationCompleted = AddressOf Me.OnReadMultipleOperationCompleted
            End If
            Me.InvokeAsync("ReadMultiple", New Object() {filter, bookmarkKey, setSize}, Me.ReadMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadMultipleCompleted(Me, New ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/clientes:IsUpdated", RequestNamespace:="urn:microsoft-dynamics-schemas/page/clientes", ResponseElementName:="IsUpdated_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/clientes", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsUpdated(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")> Boolean
            Dim results() As Object = Me.Invoke("IsUpdated", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub IsUpdatedAsync(ByVal Key As String)
            Me.IsUpdatedAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub IsUpdatedAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.IsUpdatedOperationCompleted Is Nothing) Then
                Me.IsUpdatedOperationCompleted = AddressOf Me.OnIsUpdatedOperationCompleted
            End If
            Me.InvokeAsync("IsUpdated", New Object() {Key}, Me.IsUpdatedOperationCompleted, userState)
        End Sub
        
        Private Sub OnIsUpdatedOperationCompleted(ByVal arg As Object)
            If (Not (Me.IsUpdatedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent IsUpdatedCompleted(Me, New IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/clientes:GetRecIdFromKey", RequestNamespace:="urn:microsoft-dynamics-schemas/page/clientes", ResponseElementName:="GetRecIdFromKey_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/clientes", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRecIdFromKey(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")> String
            Dim results() As Object = Me.Invoke("GetRecIdFromKey", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetRecIdFromKeyAsync(ByVal Key As String)
            Me.GetRecIdFromKeyAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetRecIdFromKeyAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.GetRecIdFromKeyOperationCompleted Is Nothing) Then
                Me.GetRecIdFromKeyOperationCompleted = AddressOf Me.OnGetRecIdFromKeyOperationCompleted
            End If
            Me.InvokeAsync("GetRecIdFromKey", New Object() {Key}, Me.GetRecIdFromKeyOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetRecIdFromKeyOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetRecIdFromKeyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetRecIdFromKeyCompleted(Me, New GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/clientes:Create", RequestNamespace:="urn:microsoft-dynamics-schemas/page/clientes", ResponseElementName:="Create_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/clientes", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Create(ByRef Clientes As Clientes)
            Dim results() As Object = Me.Invoke("Create", New Object() {Clientes})
            Clientes = CType(results(0),Clientes)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateAsync(ByVal Clientes As Clientes)
            Me.CreateAsync(Clientes, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateAsync(ByVal Clientes As Clientes, ByVal userState As Object)
            If (Me.CreateOperationCompleted Is Nothing) Then
                Me.CreateOperationCompleted = AddressOf Me.OnCreateOperationCompleted
            End If
            Me.InvokeAsync("Create", New Object() {Clientes}, Me.CreateOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateCompleted(Me, New CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/clientes:CreateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/clientes", ResponseElementName:="CreateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/clientes", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub CreateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef Clientes_List() As Clientes)
            Dim results() As Object = Me.Invoke("CreateMultiple", New Object() {Clientes_List})
            Clientes_List = CType(results(0),Clientes())
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateMultipleAsync(ByVal Clientes_List() As Clientes)
            Me.CreateMultipleAsync(Clientes_List, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateMultipleAsync(ByVal Clientes_List() As Clientes, ByVal userState As Object)
            If (Me.CreateMultipleOperationCompleted Is Nothing) Then
                Me.CreateMultipleOperationCompleted = AddressOf Me.OnCreateMultipleOperationCompleted
            End If
            Me.InvokeAsync("CreateMultiple", New Object() {Clientes_List}, Me.CreateMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateMultipleCompleted(Me, New CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/clientes:Update", RequestNamespace:="urn:microsoft-dynamics-schemas/page/clientes", ResponseElementName:="Update_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/clientes", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Update(ByRef Clientes As Clientes)
            Dim results() As Object = Me.Invoke("Update", New Object() {Clientes})
            Clientes = CType(results(0),Clientes)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal Clientes As Clientes)
            Me.UpdateAsync(Clientes, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal Clientes As Clientes, ByVal userState As Object)
            If (Me.UpdateOperationCompleted Is Nothing) Then
                Me.UpdateOperationCompleted = AddressOf Me.OnUpdateOperationCompleted
            End If
            Me.InvokeAsync("Update", New Object() {Clientes}, Me.UpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCompleted(Me, New UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/clientes:UpdateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/clientes", ResponseElementName:="UpdateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/clientes", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef Clientes_List() As Clientes)
            Dim results() As Object = Me.Invoke("UpdateMultiple", New Object() {Clientes_List})
            Clientes_List = CType(results(0),Clientes())
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateMultipleAsync(ByVal Clientes_List() As Clientes)
            Me.UpdateMultipleAsync(Clientes_List, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateMultipleAsync(ByVal Clientes_List() As Clientes, ByVal userState As Object)
            If (Me.UpdateMultipleOperationCompleted Is Nothing) Then
                Me.UpdateMultipleOperationCompleted = AddressOf Me.OnUpdateMultipleOperationCompleted
            End If
            Me.InvokeAsync("UpdateMultiple", New Object() {Clientes_List}, Me.UpdateMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateMultipleCompleted(Me, New UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/clientes:Delete", RequestNamespace:="urn:microsoft-dynamics-schemas/page/clientes", ResponseElementName:="Delete_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/clientes", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Delete(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("Delete_Result")> Boolean
            Dim results() As Object = Me.Invoke("Delete", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeleteAsync(ByVal Key As String)
            Me.DeleteAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.DeleteOperationCompleted Is Nothing) Then
                Me.DeleteOperationCompleted = AddressOf Me.OnDeleteOperationCompleted
            End If
            Me.InvokeAsync("Delete", New Object() {Key}, Me.DeleteOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteCompleted(Me, New DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/clientes")>  _
    Partial Public Class Clientes
        
        Private keyField As String
        
        Private noField As String
        
        Private nameField As String
        
        Private addressField As String
        
        Private post_CodeField As String
        
        Private cityField As String
        
        Private countyField As String
        
        Private country_Region_CodeField As String
        
        Private contactField As String
        
        Private phone_NoField As String
        
        Private fax_NoField As String
        
        Private vAT_Registration_NoField As String
        
        Private payment_Method_CodeField As String
        
        Private payment_Terms_CodeField As String
        
        Private e_MailField As String
        
        Private customer_Posting_GroupField As String
        
        Private gen_Bus_Posting_GroupField As String
        
        Private vAT_Bus_Posting_GroupField As String
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property No() As String
            Get
                Return Me.noField
            End Get
            Set
                Me.noField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address() As String
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Post_Code() As String
            Get
                Return Me.post_CodeField
            End Get
            Set
                Me.post_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property County() As String
            Get
                Return Me.countyField
            End Get
            Set
                Me.countyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Country_Region_Code() As String
            Get
                Return Me.country_Region_CodeField
            End Get
            Set
                Me.country_Region_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Contact() As String
            Get
                Return Me.contactField
            End Get
            Set
                Me.contactField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Phone_No() As String
            Get
                Return Me.phone_NoField
            End Get
            Set
                Me.phone_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fax_No() As String
            Get
                Return Me.fax_NoField
            End Get
            Set
                Me.fax_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VAT_Registration_No() As String
            Get
                Return Me.vAT_Registration_NoField
            End Get
            Set
                Me.vAT_Registration_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payment_Method_Code() As String
            Get
                Return Me.payment_Method_CodeField
            End Get
            Set
                Me.payment_Method_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payment_Terms_Code() As String
            Get
                Return Me.payment_Terms_CodeField
            End Get
            Set
                Me.payment_Terms_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E_Mail() As String
            Get
                Return Me.e_MailField
            End Get
            Set
                Me.e_MailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Customer_Posting_Group() As String
            Get
                Return Me.customer_Posting_GroupField
            End Get
            Set
                Me.customer_Posting_GroupField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Gen_Bus_Posting_Group() As String
            Get
                Return Me.gen_Bus_Posting_GroupField
            End Get
            Set
                Me.gen_Bus_Posting_GroupField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VAT_Bus_Posting_Group() As String
            Get
                Return Me.vAT_Bus_Posting_GroupField
            End Get
            Set
                Me.vAT_Bus_Posting_GroupField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/clientes")>  _
    Partial Public Class Clientes_Filter
        
        Private fieldField As Clientes_Fields
        
        Private criteriaField As String
        
        '''<remarks/>
        Public Property Field() As Clientes_Fields
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Criteria() As String
            Get
                Return Me.criteriaField
            End Get
            Set
                Me.criteriaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/clientes")>  _
    Public Enum Clientes_Fields
        
        '''<remarks/>
        No
        
        '''<remarks/>
        Name
        
        '''<remarks/>
        Address
        
        '''<remarks/>
        Post_Code
        
        '''<remarks/>
        City
        
        '''<remarks/>
        County
        
        '''<remarks/>
        Country_Region_Code
        
        '''<remarks/>
        Contact
        
        '''<remarks/>
        Phone_No
        
        '''<remarks/>
        Fax_No
        
        '''<remarks/>
        VAT_Registration_No
        
        '''<remarks/>
        Payment_Method_Code
        
        '''<remarks/>
        Payment_Terms_Code
        
        '''<remarks/>
        E_Mail
        
        '''<remarks/>
        Customer_Posting_Group
        
        '''<remarks/>
        Gen_Bus_Posting_Group
        
        '''<remarks/>
        VAT_Bus_Posting_Group
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ReadCompletedEventHandler(ByVal sender As Object, ByVal e As ReadCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Clientes
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Clientes)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ReadByRecIdCompletedEventHandler(ByVal sender As Object, ByVal e As ReadByRecIdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadByRecIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Clientes
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Clientes)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ReadMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As ReadMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Clientes()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Clientes())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub IsUpdatedCompletedEventHandler(ByVal sender As Object, ByVal e As IsUpdatedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class IsUpdatedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetRecIdFromKeyCompletedEventHandler(ByVal sender As Object, ByVal e As GetRecIdFromKeyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetRecIdFromKeyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub CreateCompletedEventHandler(ByVal sender As Object, ByVal e As CreateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Clientes() As Clientes
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Clientes)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub CreateMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As CreateMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Clientes_List() As Clientes()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Clientes())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub UpdateCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Clientes() As Clientes
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Clientes)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub UpdateMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Clientes_List() As Clientes()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Clientes())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub DeleteCompletedEventHandler(ByVal sender As Object, ByVal e As DeleteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeleteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
