'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WebReferenceFacturas
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SAT_NHCreateSalesOrdersQueryServiceSoap", [Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHCreateSalesOrdersQu"& _ 
        "ery")>  _
    Partial Public Class SAT_NHCreateSalesOrdersQueryService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private createListSAT_NHCreateSalesOrdersQueryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Menu.My.MySettings.Default.Menu_WebReferenceFacturas2_SAT_NHCreateSalesOrdersQueryService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event createListSAT_NHCreateSalesOrdersQueryCompleted As createListSAT_NHCreateSalesOrdersQueryCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHCreateSalesOrdersQu"& _ 
            "ery/createListSAT_NHCreateSalesOrdersQuery", RequestNamespace:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHCreateSalesOrdersQu"& _ 
            "ery", ResponseNamespace:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHCreateSalesOrdersQu"& _ 
            "ery", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function createListSAT_NHCreateSalesOrdersQuery(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal DocumentContext As DocumentContext, ByVal SAT_NHCreateSalesOrdersQuery As AxdSAT_NHCreateSalesOrdersQuery) As <System.Xml.Serialization.XmlArrayAttribute("EntityKeyList", [Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList"), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable:=false)> EntityKey()
            Dim results() As Object = Me.Invoke("createListSAT_NHCreateSalesOrdersQuery", New Object() {DocumentContext, SAT_NHCreateSalesOrdersQuery})
            Return CType(results(0),EntityKey())
        End Function
        
        '''<remarks/>
        Public Overloads Sub createListSAT_NHCreateSalesOrdersQueryAsync(ByVal DocumentContext As DocumentContext, ByVal SAT_NHCreateSalesOrdersQuery As AxdSAT_NHCreateSalesOrdersQuery)
            Me.createListSAT_NHCreateSalesOrdersQueryAsync(DocumentContext, SAT_NHCreateSalesOrdersQuery, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub createListSAT_NHCreateSalesOrdersQueryAsync(ByVal DocumentContext As DocumentContext, ByVal SAT_NHCreateSalesOrdersQuery As AxdSAT_NHCreateSalesOrdersQuery, ByVal userState As Object)
            If (Me.createListSAT_NHCreateSalesOrdersQueryOperationCompleted Is Nothing) Then
                Me.createListSAT_NHCreateSalesOrdersQueryOperationCompleted = AddressOf Me.OncreateListSAT_NHCreateSalesOrdersQueryOperationCompleted
            End If
            Me.InvokeAsync("createListSAT_NHCreateSalesOrdersQuery", New Object() {DocumentContext, SAT_NHCreateSalesOrdersQuery}, Me.createListSAT_NHCreateSalesOrdersQueryOperationCompleted, userState)
        End Sub
        
        Private Sub OncreateListSAT_NHCreateSalesOrdersQueryOperationCompleted(ByVal arg As Object)
            If (Not (Me.createListSAT_NHCreateSalesOrdersQueryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent createListSAT_NHCreateSalesOrdersQueryCompleted(Me, New createListSAT_NHCreateSalesOrdersQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHCreateSalesOrdersQu"& _ 
        "ery")>  _
    Partial Public Class DocumentContext
        
        Private messageIdField As String
        
        Private sourceEndpointUserField As String
        
        Private sourceEndpointField As String
        
        Private destinationEndpointField As String
        
        '''<comentarios/>
        Public Property MessageId() As String
            Get
                Return Me.messageIdField
            End Get
            Set
                Me.messageIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SourceEndpointUser() As String
            Get
                Return Me.sourceEndpointUserField
            End Get
            Set
                Me.sourceEndpointUserField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SourceEndpoint() As String
            Get
                Return Me.sourceEndpointField
            End Get
            Set
                Me.sourceEndpointField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property DestinationEndpoint() As String
            Get
                Return Me.destinationEndpointField
            End Get
            Set
                Me.destinationEndpointField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")>  _
    Partial Public Class KeyField
        
        Private fieldField As String
        
        Private valueField As String
        
        '''<comentarios/>
        Public Property Field() As String
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")>  _
    Partial Public Class EntityKey
        
        Private keyDataField() As KeyField
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property KeyData() As KeyField()
            Get
                Return Me.keyDataField
            End Get
            Set
                Me.keyDataField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHCreateSalesOrdersQu"& _ 
        "ery")>  _
    Partial Public Class AxdEntity_SAT_NHCreateSalesOrdersTaxLine_1
        
        Private lineNumField As System.Nullable(Of Integer)
        
        Private lineNumFieldSpecified As Boolean
        
        Private recIdField As System.Nullable(Of Long)
        
        Private recIdFieldSpecified As Boolean
        
        Private recVersionField As System.Nullable(Of Integer)
        
        Private recVersionFieldSpecified As Boolean
        
        Private salesOrderIdField As String
        
        Private taxAmountField As System.Nullable(Of Decimal)
        
        Private taxAmountFieldSpecified As Boolean
        
        Private taxBaseField As System.Nullable(Of Decimal)
        
        Private taxBaseFieldSpecified As Boolean
        
        Private taxCodeField As String
        
        Private taxPercentField As System.Nullable(Of Decimal)
        
        Private taxPercentFieldSpecified As Boolean
        
        Private classField As String
        
        Public Sub New()
            MyBase.New
            Me.classField = "entity"
        End Sub
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property LineNum() As System.Nullable(Of Integer)
            Get
                Return Me.lineNumField
            End Get
            Set
                Me.lineNumField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property LineNumSpecified() As Boolean
            Get
                Return Me.lineNumFieldSpecified
            End Get
            Set
                Me.lineNumFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RecId() As System.Nullable(Of Long)
            Get
                Return Me.recIdField
            End Get
            Set
                Me.recIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RecIdSpecified() As Boolean
            Get
                Return Me.recIdFieldSpecified
            End Get
            Set
                Me.recIdFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RecVersion() As System.Nullable(Of Integer)
            Get
                Return Me.recVersionField
            End Get
            Set
                Me.recVersionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RecVersionSpecified() As Boolean
            Get
                Return Me.recVersionFieldSpecified
            End Get
            Set
                Me.recVersionFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SalesOrderId() As String
            Get
                Return Me.salesOrderIdField
            End Get
            Set
                Me.salesOrderIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TaxAmount() As System.Nullable(Of Decimal)
            Get
                Return Me.taxAmountField
            End Get
            Set
                Me.taxAmountField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TaxAmountSpecified() As Boolean
            Get
                Return Me.taxAmountFieldSpecified
            End Get
            Set
                Me.taxAmountFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TaxBase() As System.Nullable(Of Decimal)
            Get
                Return Me.taxBaseField
            End Get
            Set
                Me.taxBaseField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TaxBaseSpecified() As Boolean
            Get
                Return Me.taxBaseFieldSpecified
            End Get
            Set
                Me.taxBaseFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TaxCode() As String
            Get
                Return Me.taxCodeField
            End Get
            Set
                Me.taxCodeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TaxPercent() As System.Nullable(Of Decimal)
            Get
                Return Me.taxPercentField
            End Get
            Set
                Me.taxPercentField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TaxPercentSpecified() As Boolean
            Get
                Return Me.taxPercentFieldSpecified
            End Get
            Set
                Me.taxPercentFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property [class]() As String
            Get
                Return Me.classField
            End Get
            Set
                Me.classField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHCreateSalesOrdersQu"& _ 
        "ery")>  _
    Partial Public Class AxdEntity_SAT_NHCreateSalesOrdersLine_1
        
        Private itemIdField As String
        
        Private lineNumField As System.Nullable(Of Integer)
        
        Private lineNumFieldSpecified As Boolean
        
        Private qtyField As System.Nullable(Of Decimal)
        
        Private qtyFieldSpecified As Boolean
        
        Private recIdField As System.Nullable(Of Long)
        
        Private recIdFieldSpecified As Boolean
        
        Private recVersionField As System.Nullable(Of Integer)
        
        Private recVersionFieldSpecified As Boolean
        
        Private refRecIdSalesLineField As System.Nullable(Of Long)
        
        Private refRecIdSalesLineFieldSpecified As Boolean
        
        Private salesOrderIdField As String
        
        Private salesPriceField As System.Nullable(Of Decimal)
        
        Private salesPriceFieldSpecified As Boolean
        
        Private sAT_NHCreateSalesOrdersTaxLine_1Field() As AxdEntity_SAT_NHCreateSalesOrdersTaxLine_1
        
        Private classField As String
        
        Public Sub New()
            MyBase.New
            Me.classField = "entity"
        End Sub
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ItemId() As String
            Get
                Return Me.itemIdField
            End Get
            Set
                Me.itemIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property LineNum() As System.Nullable(Of Integer)
            Get
                Return Me.lineNumField
            End Get
            Set
                Me.lineNumField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property LineNumSpecified() As Boolean
            Get
                Return Me.lineNumFieldSpecified
            End Get
            Set
                Me.lineNumFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Qty() As System.Nullable(Of Decimal)
            Get
                Return Me.qtyField
            End Get
            Set
                Me.qtyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QtySpecified() As Boolean
            Get
                Return Me.qtyFieldSpecified
            End Get
            Set
                Me.qtyFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RecId() As System.Nullable(Of Long)
            Get
                Return Me.recIdField
            End Get
            Set
                Me.recIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RecIdSpecified() As Boolean
            Get
                Return Me.recIdFieldSpecified
            End Get
            Set
                Me.recIdFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RecVersion() As System.Nullable(Of Integer)
            Get
                Return Me.recVersionField
            End Get
            Set
                Me.recVersionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RecVersionSpecified() As Boolean
            Get
                Return Me.recVersionFieldSpecified
            End Get
            Set
                Me.recVersionFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RefRecIdSalesLine() As System.Nullable(Of Long)
            Get
                Return Me.refRecIdSalesLineField
            End Get
            Set
                Me.refRecIdSalesLineField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RefRecIdSalesLineSpecified() As Boolean
            Get
                Return Me.refRecIdSalesLineFieldSpecified
            End Get
            Set
                Me.refRecIdSalesLineFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SalesOrderId() As String
            Get
                Return Me.salesOrderIdField
            End Get
            Set
                Me.salesOrderIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SalesPrice() As System.Nullable(Of Decimal)
            Get
                Return Me.salesPriceField
            End Get
            Set
                Me.salesPriceField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SalesPriceSpecified() As Boolean
            Get
                Return Me.salesPriceFieldSpecified
            End Get
            Set
                Me.salesPriceFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("SAT_NHCreateSalesOrdersTaxLine_1")>  _
        Public Property SAT_NHCreateSalesOrdersTaxLine_1() As AxdEntity_SAT_NHCreateSalesOrdersTaxLine_1()
            Get
                Return Me.sAT_NHCreateSalesOrdersTaxLine_1Field
            End Get
            Set
                Me.sAT_NHCreateSalesOrdersTaxLine_1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property [class]() As String
            Get
                Return Me.classField
            End Get
            Set
                Me.classField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHCreateSalesOrdersQu"& _ 
        "ery")>  _
    Partial Public Class AxdEntity_SAT_NHCreateSalesOrdersTable_1
        
        Private bondField As System.Nullable(Of AxdExtType_NoYesId)
        
        Private bondFieldSpecified As Boolean
        
        Private bookIdField As String
        
        Private contClientField As System.Nullable(Of AxdExtType_NoYesId)
        
        Private contClientFieldSpecified As Boolean
        
        Private custAccountField As String
        
        Private documentDateField As System.Nullable(Of Date)
        
        Private documentDateFieldSpecified As Boolean
        
        Private fixedDueDateField As System.Nullable(Of Date)
        
        Private fixedDueDateFieldSpecified As Boolean
        
        Private hotelIdField As String
        
        Private invoiceDateField As Date
        
        Private invoiceIdField As String
        
        Private nHCustAccountField As String
        
        Private recIdField As System.Nullable(Of Long)
        
        Private recIdFieldSpecified As Boolean
        
        Private recVersionField As System.Nullable(Of Integer)
        
        Private recVersionFieldSpecified As Boolean
        
        Private salesAmountField As System.Nullable(Of Decimal)
        
        Private salesAmountFieldSpecified As Boolean
        
        Private salesOrderIdField As String
        
        Private vATNumField As String
        
        Private sAT_NHCreateSalesOrdersLine_1Field() As AxdEntity_SAT_NHCreateSalesOrdersLine_1
        
        Private classField As String
        
        Public Sub New()
            MyBase.New
            Me.classField = "entity"
        End Sub
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Bond() As System.Nullable(Of AxdExtType_NoYesId)
            Get
                Return Me.bondField
            End Get
            Set
                Me.bondField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property BondSpecified() As Boolean
            Get
                Return Me.bondFieldSpecified
            End Get
            Set
                Me.bondFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property BookId() As String
            Get
                Return Me.bookIdField
            End Get
            Set
                Me.bookIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ContClient() As System.Nullable(Of AxdExtType_NoYesId)
            Get
                Return Me.contClientField
            End Get
            Set
                Me.contClientField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ContClientSpecified() As Boolean
            Get
                Return Me.contClientFieldSpecified
            End Get
            Set
                Me.contClientFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CustAccount() As String
            Get
                Return Me.custAccountField
            End Get
            Set
                Me.custAccountField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=true)>  _
        Public Property DocumentDate() As System.Nullable(Of Date)
            Get
                Return Me.documentDateField
            End Get
            Set
                Me.documentDateField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DocumentDateSpecified() As Boolean
            Get
                Return Me.documentDateFieldSpecified
            End Get
            Set
                Me.documentDateFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=true)>  _
        Public Property FixedDueDate() As System.Nullable(Of Date)
            Get
                Return Me.fixedDueDateField
            End Get
            Set
                Me.fixedDueDateField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FixedDueDateSpecified() As Boolean
            Get
                Return Me.fixedDueDateFieldSpecified
            End Get
            Set
                Me.fixedDueDateFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property HotelId() As String
            Get
                Return Me.hotelIdField
            End Get
            Set
                Me.hotelIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property InvoiceDate() As Date
            Get
                Return Me.invoiceDateField
            End Get
            Set
                Me.invoiceDateField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property InvoiceId() As String
            Get
                Return Me.invoiceIdField
            End Get
            Set
                Me.invoiceIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property NHCustAccount() As String
            Get
                Return Me.nHCustAccountField
            End Get
            Set
                Me.nHCustAccountField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RecId() As System.Nullable(Of Long)
            Get
                Return Me.recIdField
            End Get
            Set
                Me.recIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RecIdSpecified() As Boolean
            Get
                Return Me.recIdFieldSpecified
            End Get
            Set
                Me.recIdFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RecVersion() As System.Nullable(Of Integer)
            Get
                Return Me.recVersionField
            End Get
            Set
                Me.recVersionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RecVersionSpecified() As Boolean
            Get
                Return Me.recVersionFieldSpecified
            End Get
            Set
                Me.recVersionFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SalesAmount() As System.Nullable(Of Decimal)
            Get
                Return Me.salesAmountField
            End Get
            Set
                Me.salesAmountField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SalesAmountSpecified() As Boolean
            Get
                Return Me.salesAmountFieldSpecified
            End Get
            Set
                Me.salesAmountFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SalesOrderId() As String
            Get
                Return Me.salesOrderIdField
            End Get
            Set
                Me.salesOrderIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property VATNum() As String
            Get
                Return Me.vATNumField
            End Get
            Set
                Me.vATNumField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("SAT_NHCreateSalesOrdersLine_1")>  _
        Public Property SAT_NHCreateSalesOrdersLine_1() As AxdEntity_SAT_NHCreateSalesOrdersLine_1()
            Get
                Return Me.sAT_NHCreateSalesOrdersLine_1Field
            End Get
            Set
                Me.sAT_NHCreateSalesOrdersLine_1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property [class]() As String
            Get
                Return Me.classField
            End Get
            Set
                Me.classField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHCreateSalesOrdersQu"& _ 
        "ery")>  _
    Public Enum AxdExtType_NoYesId
        
        '''<comentarios/>
        No
        
        '''<comentarios/>
        Yes
    End Enum
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHCreateSalesOrdersQu"& _ 
        "ery")>  _
    Partial Public Class AxdSAT_NHCreateSalesOrdersQuery
        
        Private docPurposeField As System.Nullable(Of AxdEnum_XMLDocPurpose)
        
        Private docPurposeFieldSpecified As Boolean
        
        Private senderIdField As String
        
        Private sAT_NHCreateSalesOrdersTable_1Field() As AxdEntity_SAT_NHCreateSalesOrdersTable_1
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DocPurpose() As System.Nullable(Of AxdEnum_XMLDocPurpose)
            Get
                Return Me.docPurposeField
            End Get
            Set
                Me.docPurposeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DocPurposeSpecified() As Boolean
            Get
                Return Me.docPurposeFieldSpecified
            End Get
            Set
                Me.docPurposeFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SenderId() As String
            Get
                Return Me.senderIdField
            End Get
            Set
                Me.senderIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("SAT_NHCreateSalesOrdersTable_1")>  _
        Public Property SAT_NHCreateSalesOrdersTable_1() As AxdEntity_SAT_NHCreateSalesOrdersTable_1()
            Get
                Return Me.sAT_NHCreateSalesOrdersTable_1Field
            End Get
            Set
                Me.sAT_NHCreateSalesOrdersTable_1Field = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHCreateSalesOrdersQu"& _ 
        "ery")>  _
    Public Enum AxdEnum_XMLDocPurpose
        
        '''<comentarios/>
        Original
        
        '''<comentarios/>
        Duplicate
        
        '''<comentarios/>
        Proforma
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub createListSAT_NHCreateSalesOrdersQueryCompletedEventHandler(ByVal sender As Object, ByVal e As createListSAT_NHCreateSalesOrdersQueryCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class createListSAT_NHCreateSalesOrdersQueryCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EntityKey()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EntityKey())
            End Get
        End Property
    End Class
End Namespace
