'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WebReferenceAnticipos
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SAT_NHPrePaymentServiceSoap", [Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHPrePayment")>  _
    Partial Public Class SAT_NHPrePaymentService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SendPrePaymentOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Menu.My.MySettings.Default.Menu_WebReferenceAnticipos2_SAT_NHPrePaymentService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SendPrePaymentCompleted As SendPrePaymentCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHPrePayment/SendPreP"& _ 
            "ayment", RequestNamespace:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHPrePayment", ResponseNamespace:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHPrePayment", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendPrePayment(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal DocumentContext As DocumentContext, ByVal SAT_NHPrePayment As AxdSAT_NHPrePayment) As <System.Xml.Serialization.XmlArrayAttribute("EntityKeyList", [Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList"), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable:=false)> EntityKey()
            Dim results() As Object = Me.Invoke("SendPrePayment", New Object() {DocumentContext, SAT_NHPrePayment})
            Return CType(results(0),EntityKey())
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendPrePaymentAsync(ByVal DocumentContext As DocumentContext, ByVal SAT_NHPrePayment As AxdSAT_NHPrePayment)
            Me.SendPrePaymentAsync(DocumentContext, SAT_NHPrePayment, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendPrePaymentAsync(ByVal DocumentContext As DocumentContext, ByVal SAT_NHPrePayment As AxdSAT_NHPrePayment, ByVal userState As Object)
            If (Me.SendPrePaymentOperationCompleted Is Nothing) Then
                Me.SendPrePaymentOperationCompleted = AddressOf Me.OnSendPrePaymentOperationCompleted
            End If
            Me.InvokeAsync("SendPrePayment", New Object() {DocumentContext, SAT_NHPrePayment}, Me.SendPrePaymentOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendPrePaymentOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendPrePaymentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendPrePaymentCompleted(Me, New SendPrePaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHPrePayment")>  _
    Partial Public Class DocumentContext
        
        Private messageIdField As String
        
        Private sourceEndpointUserField As String
        
        Private sourceEndpointField As String
        
        Private destinationEndpointField As String
        
        '''<comentarios/>
        Public Property MessageId() As String
            Get
                Return Me.messageIdField
            End Get
            Set
                Me.messageIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SourceEndpointUser() As String
            Get
                Return Me.sourceEndpointUserField
            End Get
            Set
                Me.sourceEndpointUserField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SourceEndpoint() As String
            Get
                Return Me.sourceEndpointField
            End Get
            Set
                Me.sourceEndpointField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property DestinationEndpoint() As String
            Get
                Return Me.destinationEndpointField
            End Get
            Set
                Me.destinationEndpointField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")>  _
    Partial Public Class KeyField
        
        Private fieldField As String
        
        Private valueField As String
        
        '''<comentarios/>
        Public Property Field() As String
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")>  _
    Partial Public Class EntityKey
        
        Private keyDataField() As KeyField
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property KeyData() As KeyField()
            Get
                Return Me.keyDataField
            End Get
            Set
                Me.keyDataField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHPrePayment")>  _
    Partial Public Class AxdEntity_Tabla
        
        Private bookIDField As String
        
        Private contClientField As System.Nullable(Of AxdExtType_NoYesId)
        
        Private contClientFieldSpecified As Boolean
        
        Private hotelIdField As String
        
        Private paymModeField As String
        
        Private prePaymentAmountField As System.Nullable(Of Decimal)
        
        Private prePaymentAmountFieldSpecified As Boolean
        
        Private recIdField As System.Nullable(Of Long)
        
        Private recIdFieldSpecified As Boolean
        
        Private recVersionField As System.Nullable(Of Integer)
        
        Private recVersionFieldSpecified As Boolean
        
        Private transDateField As Date
        
        Private txtField As String
        
        Private vatNumField As String
        
        Private classField As String
        
        Public Sub New()
            MyBase.New
            Me.classField = "entity"
        End Sub
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property BookID() As String
            Get
                Return Me.bookIDField
            End Get
            Set
                Me.bookIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ContClient() As System.Nullable(Of AxdExtType_NoYesId)
            Get
                Return Me.contClientField
            End Get
            Set
                Me.contClientField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ContClientSpecified() As Boolean
            Get
                Return Me.contClientFieldSpecified
            End Get
            Set
                Me.contClientFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property HotelId() As String
            Get
                Return Me.hotelIdField
            End Get
            Set
                Me.hotelIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PaymMode() As String
            Get
                Return Me.paymModeField
            End Get
            Set
                Me.paymModeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PrePaymentAmount() As System.Nullable(Of Decimal)
            Get
                Return Me.prePaymentAmountField
            End Get
            Set
                Me.prePaymentAmountField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PrePaymentAmountSpecified() As Boolean
            Get
                Return Me.prePaymentAmountFieldSpecified
            End Get
            Set
                Me.prePaymentAmountFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RecId() As System.Nullable(Of Long)
            Get
                Return Me.recIdField
            End Get
            Set
                Me.recIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RecIdSpecified() As Boolean
            Get
                Return Me.recIdFieldSpecified
            End Get
            Set
                Me.recIdFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RecVersion() As System.Nullable(Of Integer)
            Get
                Return Me.recVersionField
            End Get
            Set
                Me.recVersionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RecVersionSpecified() As Boolean
            Get
                Return Me.recVersionFieldSpecified
            End Get
            Set
                Me.recVersionFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property TransDate() As Date
            Get
                Return Me.transDateField
            End Get
            Set
                Me.transDateField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Txt() As String
            Get
                Return Me.txtField
            End Get
            Set
                Me.txtField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property VatNum() As String
            Get
                Return Me.vatNumField
            End Get
            Set
                Me.vatNumField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property [class]() As String
            Get
                Return Me.classField
            End Get
            Set
                Me.classField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHPrePayment")>  _
    Public Enum AxdExtType_NoYesId
        
        '''<comentarios/>
        No
        
        '''<comentarios/>
        Yes
    End Enum
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHPrePayment")>  _
    Partial Public Class AxdSAT_NHPrePayment
        
        Private docPurposeField As System.Nullable(Of AxdEnum_XMLDocPurpose)
        
        Private docPurposeFieldSpecified As Boolean
        
        Private senderIdField As String
        
        Private tablaField() As AxdEntity_Tabla
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DocPurpose() As System.Nullable(Of AxdEnum_XMLDocPurpose)
            Get
                Return Me.docPurposeField
            End Get
            Set
                Me.docPurposeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DocPurposeSpecified() As Boolean
            Get
                Return Me.docPurposeFieldSpecified
            End Get
            Set
                Me.docPurposeFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SenderId() As String
            Get
                Return Me.senderIdField
            End Get
            Set
                Me.senderIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("Tabla")>  _
        Public Property Tabla() As AxdEntity_Tabla()
            Get
                Return Me.tablaField
            End Get
            Set
                Me.tablaField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHPrePayment")>  _
    Public Enum AxdEnum_XMLDocPurpose
        
        '''<comentarios/>
        Original
        
        '''<comentarios/>
        Duplicate
        
        '''<comentarios/>
        Proforma
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub SendPrePaymentCompletedEventHandler(ByVal sender As Object, ByVal e As SendPrePaymentCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendPrePaymentCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EntityKey()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EntityKey())
            End Get
        End Property
    End Class
End Namespace
