'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WebReferenceCompras
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SAT_NHVendPackingSlipJourServiceSoap", [Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHVendPackingSlipJour"& _ 
        "")>  _
    Partial Public Class SAT_NHVendPackingSlipJourService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private createListSAT_NHVendPackingSlipJourOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Menu.My.MySettings.Default.Menu_WebReferenceCompras2_SAT_NHVendPackingSlipJourService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event createListSAT_NHVendPackingSlipJourCompleted As createListSAT_NHVendPackingSlipJourCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHVendPackingSlipJour"& _ 
            "/createListSAT_NHVendPackingSlipJour", RequestNamespace:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHVendPackingSlipJour"& _ 
            "", ResponseNamespace:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHVendPackingSlipJour"& _ 
            "", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function createListSAT_NHVendPackingSlipJour(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal DocumentContext As DocumentContext, ByVal SAT_NHVendPackingSlipJour As AxdSAT_NHVendPackingSlipJour) As <System.Xml.Serialization.XmlArrayAttribute("EntityKeyList", [Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKeyList"), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey", IsNullable:=false)> EntityKey()
            Dim results() As Object = Me.Invoke("createListSAT_NHVendPackingSlipJour", New Object() {DocumentContext, SAT_NHVendPackingSlipJour})
            Return CType(results(0),EntityKey())
        End Function
        
        '''<remarks/>
        Public Overloads Sub createListSAT_NHVendPackingSlipJourAsync(ByVal DocumentContext As DocumentContext, ByVal SAT_NHVendPackingSlipJour As AxdSAT_NHVendPackingSlipJour)
            Me.createListSAT_NHVendPackingSlipJourAsync(DocumentContext, SAT_NHVendPackingSlipJour, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub createListSAT_NHVendPackingSlipJourAsync(ByVal DocumentContext As DocumentContext, ByVal SAT_NHVendPackingSlipJour As AxdSAT_NHVendPackingSlipJour, ByVal userState As Object)
            If (Me.createListSAT_NHVendPackingSlipJourOperationCompleted Is Nothing) Then
                Me.createListSAT_NHVendPackingSlipJourOperationCompleted = AddressOf Me.OncreateListSAT_NHVendPackingSlipJourOperationCompleted
            End If
            Me.InvokeAsync("createListSAT_NHVendPackingSlipJour", New Object() {DocumentContext, SAT_NHVendPackingSlipJour}, Me.createListSAT_NHVendPackingSlipJourOperationCompleted, userState)
        End Sub
        
        Private Sub OncreateListSAT_NHVendPackingSlipJourOperationCompleted(ByVal arg As Object)
            If (Not (Me.createListSAT_NHVendPackingSlipJourCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent createListSAT_NHVendPackingSlipJourCompleted(Me, New createListSAT_NHVendPackingSlipJourCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHVendPackingSlipJour"& _ 
        "")>  _
    Partial Public Class DocumentContext
        
        Private messageIdField As String
        
        Private sourceEndpointUserField As String
        
        Private sourceEndpointField As String
        
        Private destinationEndpointField As String
        
        '''<comentarios/>
        Public Property MessageId() As String
            Get
                Return Me.messageIdField
            End Get
            Set
                Me.messageIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SourceEndpointUser() As String
            Get
                Return Me.sourceEndpointUserField
            End Get
            Set
                Me.sourceEndpointUserField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SourceEndpoint() As String
            Get
                Return Me.sourceEndpointField
            End Get
            Set
                Me.sourceEndpointField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property DestinationEndpoint() As String
            Get
                Return Me.destinationEndpointField
            End Get
            Set
                Me.destinationEndpointField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")>  _
    Partial Public Class KeyField
        
        Private fieldField As String
        
        Private valueField As String
        
        '''<comentarios/>
        Public Property Field() As String
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/EntityKey")>  _
    Partial Public Class EntityKey
        
        Private keyDataField() As KeyField
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property KeyData() As KeyField()
            Get
                Return Me.keyDataField
            End Get
            Set
                Me.keyDataField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHVendPackingSlipJour"& _ 
        "")>  _
    Partial Public Class AxdEntity_SAT_NHVendPackingSlipTrans
        
        Private aLMA_CODIField As System.Nullable(Of Decimal)
        
        Private aLMA_CODIFieldSpecified As Boolean
        
        Private amountVATField As System.Nullable(Of Decimal)
        
        Private amountVATFieldSpecified As Boolean
        
        Private cAPR_CODIField As System.Nullable(Of Decimal)
        
        Private cAPR_CODIFieldSpecified As Boolean
        
        Private dtoPercentField As System.Nullable(Of Decimal)
        
        Private dtoPercentFieldSpecified As Boolean
        
        Private dtoValueField As System.Nullable(Of Decimal)
        
        Private dtoValueFieldSpecified As Boolean
        
        Private holdBackValueField As System.Nullable(Of Decimal)
        
        Private holdBackValueFieldSpecified As Boolean
        
        Private itemNHInternalField As String
        
        Private iVAS_CODIField As System.Nullable(Of Decimal)
        
        Private iVAS_CODIFieldSpecified As Boolean
        
        Private lineAmountField As System.Nullable(Of Decimal)
        
        Private lineAmountFieldSpecified As Boolean
        
        Private mOVD_CODIField As System.Nullable(Of Decimal)
        
        Private mOVD_CODIFieldSpecified As Boolean
        
        Private mOVD_CONTField As System.Nullable(Of Integer)
        
        Private mOVD_CONTFieldSpecified As Boolean
        
        Private mOVD_IVASField As System.Nullable(Of Decimal)
        
        Private mOVD_IVASFieldSpecified As Boolean
        
        Private mOVG_ANCIField As System.Nullable(Of Decimal)
        
        Private mOVG_ANCIFieldSpecified As Boolean
        
        Private mOVG_CODIField As System.Nullable(Of Decimal)
        
        Private mOVG_CODIFieldSpecified As Boolean
        
        Private packingSlipIdNHField As String
        
        Private priceUnitField As System.Nullable(Of Decimal)
        
        Private priceUnitFieldSpecified As Boolean
        
        Private purchIdNHField As String
        
        Private qtyField As System.Nullable(Of Decimal)
        
        Private qtyFieldSpecified As Boolean
        
        Private qtyOrderedField As System.Nullable(Of Decimal)
        
        Private qtyOrderedFieldSpecified As Boolean
        
        Private recIdField As System.Nullable(Of Long)
        
        Private recIdFieldSpecified As Boolean
        
        Private recVersionField As System.Nullable(Of Integer)
        
        Private recVersionFieldSpecified As Boolean
        
        Private refRecIdField As System.Nullable(Of Long)
        
        Private refRecIdFieldSpecified As Boolean
        
        Private rETE_CODIField As System.Nullable(Of Decimal)
        
        Private rETE_CODIFieldSpecified As Boolean
        
        Private rETE_TAXAField As System.Nullable(Of Decimal)
        
        Private rETE_TAXAFieldSpecified As Boolean
        
        Private sAT_NHItemIdField As String
        
        Private taxValueField As System.Nullable(Of Decimal)
        
        Private taxValueFieldSpecified As Boolean
        
        Private uNME_CODIField As System.Nullable(Of Decimal)
        
        Private uNME_CODIFieldSpecified As Boolean
        
        Private classField As String
        
        Public Sub New()
            MyBase.New
            Me.classField = "entity"
        End Sub
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ALMA_CODI() As System.Nullable(Of Decimal)
            Get
                Return Me.aLMA_CODIField
            End Get
            Set
                Me.aLMA_CODIField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ALMA_CODISpecified() As Boolean
            Get
                Return Me.aLMA_CODIFieldSpecified
            End Get
            Set
                Me.aLMA_CODIFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property AmountVAT() As System.Nullable(Of Decimal)
            Get
                Return Me.amountVATField
            End Get
            Set
                Me.amountVATField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AmountVATSpecified() As Boolean
            Get
                Return Me.amountVATFieldSpecified
            End Get
            Set
                Me.amountVATFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CAPR_CODI() As System.Nullable(Of Decimal)
            Get
                Return Me.cAPR_CODIField
            End Get
            Set
                Me.cAPR_CODIField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CAPR_CODISpecified() As Boolean
            Get
                Return Me.cAPR_CODIFieldSpecified
            End Get
            Set
                Me.cAPR_CODIFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DtoPercent() As System.Nullable(Of Decimal)
            Get
                Return Me.dtoPercentField
            End Get
            Set
                Me.dtoPercentField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DtoPercentSpecified() As Boolean
            Get
                Return Me.dtoPercentFieldSpecified
            End Get
            Set
                Me.dtoPercentFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DtoValue() As System.Nullable(Of Decimal)
            Get
                Return Me.dtoValueField
            End Get
            Set
                Me.dtoValueField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DtoValueSpecified() As Boolean
            Get
                Return Me.dtoValueFieldSpecified
            End Get
            Set
                Me.dtoValueFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property HoldBackValue() As System.Nullable(Of Decimal)
            Get
                Return Me.holdBackValueField
            End Get
            Set
                Me.holdBackValueField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property HoldBackValueSpecified() As Boolean
            Get
                Return Me.holdBackValueFieldSpecified
            End Get
            Set
                Me.holdBackValueFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ItemNHInternal() As String
            Get
                Return Me.itemNHInternalField
            End Get
            Set
                Me.itemNHInternalField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IVAS_CODI() As System.Nullable(Of Decimal)
            Get
                Return Me.iVAS_CODIField
            End Get
            Set
                Me.iVAS_CODIField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property IVAS_CODISpecified() As Boolean
            Get
                Return Me.iVAS_CODIFieldSpecified
            End Get
            Set
                Me.iVAS_CODIFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property LineAmount() As System.Nullable(Of Decimal)
            Get
                Return Me.lineAmountField
            End Get
            Set
                Me.lineAmountField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property LineAmountSpecified() As Boolean
            Get
                Return Me.lineAmountFieldSpecified
            End Get
            Set
                Me.lineAmountFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVD_CODI() As System.Nullable(Of Decimal)
            Get
                Return Me.mOVD_CODIField
            End Get
            Set
                Me.mOVD_CODIField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MOVD_CODISpecified() As Boolean
            Get
                Return Me.mOVD_CODIFieldSpecified
            End Get
            Set
                Me.mOVD_CODIFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVD_CONT() As System.Nullable(Of Integer)
            Get
                Return Me.mOVD_CONTField
            End Get
            Set
                Me.mOVD_CONTField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MOVD_CONTSpecified() As Boolean
            Get
                Return Me.mOVD_CONTFieldSpecified
            End Get
            Set
                Me.mOVD_CONTFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVD_IVAS() As System.Nullable(Of Decimal)
            Get
                Return Me.mOVD_IVASField
            End Get
            Set
                Me.mOVD_IVASField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MOVD_IVASSpecified() As Boolean
            Get
                Return Me.mOVD_IVASFieldSpecified
            End Get
            Set
                Me.mOVD_IVASFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVG_ANCI() As System.Nullable(Of Decimal)
            Get
                Return Me.mOVG_ANCIField
            End Get
            Set
                Me.mOVG_ANCIField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MOVG_ANCISpecified() As Boolean
            Get
                Return Me.mOVG_ANCIFieldSpecified
            End Get
            Set
                Me.mOVG_ANCIFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVG_CODI() As System.Nullable(Of Decimal)
            Get
                Return Me.mOVG_CODIField
            End Get
            Set
                Me.mOVG_CODIField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MOVG_CODISpecified() As Boolean
            Get
                Return Me.mOVG_CODIFieldSpecified
            End Get
            Set
                Me.mOVG_CODIFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PackingSlipIdNH() As String
            Get
                Return Me.packingSlipIdNHField
            End Get
            Set
                Me.packingSlipIdNHField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PriceUnit() As System.Nullable(Of Decimal)
            Get
                Return Me.priceUnitField
            End Get
            Set
                Me.priceUnitField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PriceUnitSpecified() As Boolean
            Get
                Return Me.priceUnitFieldSpecified
            End Get
            Set
                Me.priceUnitFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PurchIdNH() As String
            Get
                Return Me.purchIdNHField
            End Get
            Set
                Me.purchIdNHField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Qty() As System.Nullable(Of Decimal)
            Get
                Return Me.qtyField
            End Get
            Set
                Me.qtyField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QtySpecified() As Boolean
            Get
                Return Me.qtyFieldSpecified
            End Get
            Set
                Me.qtyFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property QtyOrdered() As System.Nullable(Of Decimal)
            Get
                Return Me.qtyOrderedField
            End Get
            Set
                Me.qtyOrderedField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QtyOrderedSpecified() As Boolean
            Get
                Return Me.qtyOrderedFieldSpecified
            End Get
            Set
                Me.qtyOrderedFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RecId() As System.Nullable(Of Long)
            Get
                Return Me.recIdField
            End Get
            Set
                Me.recIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RecIdSpecified() As Boolean
            Get
                Return Me.recIdFieldSpecified
            End Get
            Set
                Me.recIdFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RecVersion() As System.Nullable(Of Integer)
            Get
                Return Me.recVersionField
            End Get
            Set
                Me.recVersionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RecVersionSpecified() As Boolean
            Get
                Return Me.recVersionFieldSpecified
            End Get
            Set
                Me.recVersionFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RefRecId() As System.Nullable(Of Long)
            Get
                Return Me.refRecIdField
            End Get
            Set
                Me.refRecIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RefRecIdSpecified() As Boolean
            Get
                Return Me.refRecIdFieldSpecified
            End Get
            Set
                Me.refRecIdFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RETE_CODI() As System.Nullable(Of Decimal)
            Get
                Return Me.rETE_CODIField
            End Get
            Set
                Me.rETE_CODIField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RETE_CODISpecified() As Boolean
            Get
                Return Me.rETE_CODIFieldSpecified
            End Get
            Set
                Me.rETE_CODIFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RETE_TAXA() As System.Nullable(Of Decimal)
            Get
                Return Me.rETE_TAXAField
            End Get
            Set
                Me.rETE_TAXAField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RETE_TAXASpecified() As Boolean
            Get
                Return Me.rETE_TAXAFieldSpecified
            End Get
            Set
                Me.rETE_TAXAFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SAT_NHItemId() As String
            Get
                Return Me.sAT_NHItemIdField
            End Get
            Set
                Me.sAT_NHItemIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TaxValue() As System.Nullable(Of Decimal)
            Get
                Return Me.taxValueField
            End Get
            Set
                Me.taxValueField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TaxValueSpecified() As Boolean
            Get
                Return Me.taxValueFieldSpecified
            End Get
            Set
                Me.taxValueFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property UNME_CODI() As System.Nullable(Of Decimal)
            Get
                Return Me.uNME_CODIField
            End Get
            Set
                Me.uNME_CODIField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property UNME_CODISpecified() As Boolean
            Get
                Return Me.uNME_CODIFieldSpecified
            End Get
            Set
                Me.uNME_CODIFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property [class]() As String
            Get
                Return Me.classField
            End Get
            Set
                Me.classField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHVendPackingSlipJour"& _ 
        "")>  _
    Partial Public Class AxdEntity_SAT_NHVendPackingSlipJour
        
        Private counterLinesField As Integer
        
        Private deliveryDateField As System.Nullable(Of Date)
        
        Private deliveryDateFieldSpecified As Boolean
        
        Private dtoPercentField As System.Nullable(Of Decimal)
        
        Private dtoPercentFieldSpecified As Boolean
        
        Private dtoValueField As System.Nullable(Of Decimal)
        
        Private dtoValueFieldSpecified As Boolean
        
        Private esAnulacionField As System.Nullable(Of AxdExtType_NoYesId)
        
        Private esAnulacionFieldSpecified As Boolean
        
        Private hotelIdField As String
        
        Private isBackField As System.Nullable(Of AxdExtType_NoYesId)
        
        Private isBackFieldSpecified As Boolean
        
        Private mOVG_ANCIField As System.Nullable(Of Decimal)
        
        Private mOVG_ANCIFieldSpecified As Boolean
        
        Private mOVG_CODIField As System.Nullable(Of Decimal)
        
        Private mOVG_CODIFieldSpecified As Boolean
        
        Private mOVG_DADOField As System.Nullable(Of Date)
        
        Private mOVG_DADOFieldSpecified As Boolean
        
        Private mOVG_DESTField As System.Nullable(Of Decimal)
        
        Private mOVG_DESTFieldSpecified As Boolean
        
        Private mOVG_DOREField As String
        
        Private mOVG_IDDOField As String
        
        Private mOVG_IDIDField As String
        
        Private mOVG_ORIGField As System.Nullable(Of Decimal)
        
        Private mOVG_ORIGFieldSpecified As Boolean
        
        Private mOVG_TIDEField As System.Nullable(Of Decimal)
        
        Private mOVG_TIDEFieldSpecified As Boolean
        
        Private mOVG_TIORField As System.Nullable(Of Decimal)
        
        Private mOVG_TIORFieldSpecified As Boolean
        
        Private mOVG_VATOField As System.Nullable(Of Decimal)
        
        Private mOVG_VATOFieldSpecified As Boolean
        
        Private packingSlipIdField As String
        
        Private packingSlipIdNHField As String
        
        Private pEDG_CODIField As System.Nullable(Of Decimal)
        
        Private pEDG_CODIFieldSpecified As Boolean
        
        Private purchIdField As String
        
        Private recIdField As System.Nullable(Of Long)
        
        Private recIdFieldSpecified As Boolean
        
        Private recVersionField As System.Nullable(Of Integer)
        
        Private recVersionFieldSpecified As Boolean
        
        Private refRecIdSendField As System.Nullable(Of Long)
        
        Private refRecIdSendFieldSpecified As Boolean
        
        Private totalField As Decimal
        
        Private totalNoVatField As Decimal
        
        Private transDateField As Date
        
        Private valueDateField As Date
        
        Private vendorField As String
        
        Private sAT_NHVendPackingSlipTransField() As AxdEntity_SAT_NHVendPackingSlipTrans
        
        Private classField As String
        
        Public Sub New()
            MyBase.New
            Me.classField = "entity"
        End Sub
        
        '''<comentarios/>
        Public Property CounterLines() As Integer
            Get
                Return Me.counterLinesField
            End Get
            Set
                Me.counterLinesField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=true)>  _
        Public Property DeliveryDate() As System.Nullable(Of Date)
            Get
                Return Me.deliveryDateField
            End Get
            Set
                Me.deliveryDateField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DeliveryDateSpecified() As Boolean
            Get
                Return Me.deliveryDateFieldSpecified
            End Get
            Set
                Me.deliveryDateFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DtoPercent() As System.Nullable(Of Decimal)
            Get
                Return Me.dtoPercentField
            End Get
            Set
                Me.dtoPercentField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DtoPercentSpecified() As Boolean
            Get
                Return Me.dtoPercentFieldSpecified
            End Get
            Set
                Me.dtoPercentFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DtoValue() As System.Nullable(Of Decimal)
            Get
                Return Me.dtoValueField
            End Get
            Set
                Me.dtoValueField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DtoValueSpecified() As Boolean
            Get
                Return Me.dtoValueFieldSpecified
            End Get
            Set
                Me.dtoValueFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property EsAnulacion() As System.Nullable(Of AxdExtType_NoYesId)
            Get
                Return Me.esAnulacionField
            End Get
            Set
                Me.esAnulacionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property EsAnulacionSpecified() As Boolean
            Get
                Return Me.esAnulacionFieldSpecified
            End Get
            Set
                Me.esAnulacionFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property HotelId() As String
            Get
                Return Me.hotelIdField
            End Get
            Set
                Me.hotelIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IsBack() As System.Nullable(Of AxdExtType_NoYesId)
            Get
                Return Me.isBackField
            End Get
            Set
                Me.isBackField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property IsBackSpecified() As Boolean
            Get
                Return Me.isBackFieldSpecified
            End Get
            Set
                Me.isBackFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVG_ANCI() As System.Nullable(Of Decimal)
            Get
                Return Me.mOVG_ANCIField
            End Get
            Set
                Me.mOVG_ANCIField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MOVG_ANCISpecified() As Boolean
            Get
                Return Me.mOVG_ANCIFieldSpecified
            End Get
            Set
                Me.mOVG_ANCIFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVG_CODI() As System.Nullable(Of Decimal)
            Get
                Return Me.mOVG_CODIField
            End Get
            Set
                Me.mOVG_CODIField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MOVG_CODISpecified() As Boolean
            Get
                Return Me.mOVG_CODIFieldSpecified
            End Get
            Set
                Me.mOVG_CODIFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=true)>  _
        Public Property MOVG_DADO() As System.Nullable(Of Date)
            Get
                Return Me.mOVG_DADOField
            End Get
            Set
                Me.mOVG_DADOField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MOVG_DADOSpecified() As Boolean
            Get
                Return Me.mOVG_DADOFieldSpecified
            End Get
            Set
                Me.mOVG_DADOFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVG_DEST() As System.Nullable(Of Decimal)
            Get
                Return Me.mOVG_DESTField
            End Get
            Set
                Me.mOVG_DESTField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MOVG_DESTSpecified() As Boolean
            Get
                Return Me.mOVG_DESTFieldSpecified
            End Get
            Set
                Me.mOVG_DESTFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVG_DORE() As String
            Get
                Return Me.mOVG_DOREField
            End Get
            Set
                Me.mOVG_DOREField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVG_IDDO() As String
            Get
                Return Me.mOVG_IDDOField
            End Get
            Set
                Me.mOVG_IDDOField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVG_IDID() As String
            Get
                Return Me.mOVG_IDIDField
            End Get
            Set
                Me.mOVG_IDIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVG_ORIG() As System.Nullable(Of Decimal)
            Get
                Return Me.mOVG_ORIGField
            End Get
            Set
                Me.mOVG_ORIGField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MOVG_ORIGSpecified() As Boolean
            Get
                Return Me.mOVG_ORIGFieldSpecified
            End Get
            Set
                Me.mOVG_ORIGFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVG_TIDE() As System.Nullable(Of Decimal)
            Get
                Return Me.mOVG_TIDEField
            End Get
            Set
                Me.mOVG_TIDEField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MOVG_TIDESpecified() As Boolean
            Get
                Return Me.mOVG_TIDEFieldSpecified
            End Get
            Set
                Me.mOVG_TIDEFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVG_TIOR() As System.Nullable(Of Decimal)
            Get
                Return Me.mOVG_TIORField
            End Get
            Set
                Me.mOVG_TIORField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MOVG_TIORSpecified() As Boolean
            Get
                Return Me.mOVG_TIORFieldSpecified
            End Get
            Set
                Me.mOVG_TIORFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MOVG_VATO() As System.Nullable(Of Decimal)
            Get
                Return Me.mOVG_VATOField
            End Get
            Set
                Me.mOVG_VATOField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MOVG_VATOSpecified() As Boolean
            Get
                Return Me.mOVG_VATOFieldSpecified
            End Get
            Set
                Me.mOVG_VATOFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PackingSlipId() As String
            Get
                Return Me.packingSlipIdField
            End Get
            Set
                Me.packingSlipIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PackingSlipIdNH() As String
            Get
                Return Me.packingSlipIdNHField
            End Get
            Set
                Me.packingSlipIdNHField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PEDG_CODI() As System.Nullable(Of Decimal)
            Get
                Return Me.pEDG_CODIField
            End Get
            Set
                Me.pEDG_CODIField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PEDG_CODISpecified() As Boolean
            Get
                Return Me.pEDG_CODIFieldSpecified
            End Get
            Set
                Me.pEDG_CODIFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PurchId() As String
            Get
                Return Me.purchIdField
            End Get
            Set
                Me.purchIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RecId() As System.Nullable(Of Long)
            Get
                Return Me.recIdField
            End Get
            Set
                Me.recIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RecIdSpecified() As Boolean
            Get
                Return Me.recIdFieldSpecified
            End Get
            Set
                Me.recIdFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RecVersion() As System.Nullable(Of Integer)
            Get
                Return Me.recVersionField
            End Get
            Set
                Me.recVersionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RecVersionSpecified() As Boolean
            Get
                Return Me.recVersionFieldSpecified
            End Get
            Set
                Me.recVersionFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RefRecIdSend() As System.Nullable(Of Long)
            Get
                Return Me.refRecIdSendField
            End Get
            Set
                Me.refRecIdSendField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RefRecIdSendSpecified() As Boolean
            Get
                Return Me.refRecIdSendFieldSpecified
            End Get
            Set
                Me.refRecIdSendFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Total() As Decimal
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TotalNoVat() As Decimal
            Get
                Return Me.totalNoVatField
            End Get
            Set
                Me.totalNoVatField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property TransDate() As Date
            Get
                Return Me.transDateField
            End Get
            Set
                Me.transDateField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property ValueDate() As Date
            Get
                Return Me.valueDateField
            End Get
            Set
                Me.valueDateField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Vendor() As String
            Get
                Return Me.vendorField
            End Get
            Set
                Me.vendorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("SAT_NHVendPackingSlipTrans")>  _
        Public Property SAT_NHVendPackingSlipTrans() As AxdEntity_SAT_NHVendPackingSlipTrans()
            Get
                Return Me.sAT_NHVendPackingSlipTransField
            End Get
            Set
                Me.sAT_NHVendPackingSlipTransField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property [class]() As String
            Get
                Return Me.classField
            End Get
            Set
                Me.classField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHVendPackingSlipJour"& _ 
        "")>  _
    Public Enum AxdExtType_NoYesId
        
        '''<comentarios/>
        No
        
        '''<comentarios/>
        Yes
    End Enum
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHVendPackingSlipJour"& _ 
        "")>  _
    Partial Public Class AxdSAT_NHVendPackingSlipJour
        
        Private docPurposeField As System.Nullable(Of AxdEnum_XMLDocPurpose)
        
        Private docPurposeFieldSpecified As Boolean
        
        Private senderIdField As String
        
        Private sAT_NHVendPackingSlipJourField() As AxdEntity_SAT_NHVendPackingSlipJour
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DocPurpose() As System.Nullable(Of AxdEnum_XMLDocPurpose)
            Get
                Return Me.docPurposeField
            End Get
            Set
                Me.docPurposeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DocPurposeSpecified() As Boolean
            Get
                Return Me.docPurposeFieldSpecified
            End Get
            Set
                Me.docPurposeFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SenderId() As String
            Get
                Return Me.senderIdField
            End Get
            Set
                Me.senderIdField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("SAT_NHVendPackingSlipJour")>  _
        Public Property SAT_NHVendPackingSlipJour() As AxdEntity_SAT_NHVendPackingSlipJour()
            Get
                Return Me.sAT_NHVendPackingSlipJourField
            End Get
            Set
                Me.sAT_NHVendPackingSlipJourField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2006/02/documents/SAT_NHVendPackingSlipJour"& _ 
        "")>  _
    Public Enum AxdEnum_XMLDocPurpose
        
        '''<comentarios/>
        Original
        
        '''<comentarios/>
        Duplicate
        
        '''<comentarios/>
        Proforma
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub createListSAT_NHVendPackingSlipJourCompletedEventHandler(ByVal sender As Object, ByVal e As createListSAT_NHVendPackingSlipJourCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class createListSAT_NHVendPackingSlipJourCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EntityKey()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EntityKey())
            End Get
        End Property
    End Class
End Namespace
