SELECT T1.FACT_DAEM,T1.FACT_CODI,T1.SEFA_CODI,FACT_CONT ,sum(T2.faiv_inci)FROM RMCGHC.TNHT_FACT T1,RMCGHC.TNHT_FAIV T2 
WHERE
T1.FACT_CODI = T2.FACT_CODI AND T1.SEFA_CODI = T2.SEFA_CODI AND 

T1.FACT_STAT IN(2,3) AND T1.FACT_DAEM > '15-APR-2007' AND
T1.FACT_CONT <> (SELECT ROUND(sum(faiv_inci),2) from rmcghc.tnht_faiv T3 WHERE 
T1.FACT_CODI = T3.FACT_CODI AND T1.SEFA_CODI = T3.SEFA_CODI) GROUP BY  T1.FACT_CODI,T1.SEFA_CODI,FACT_CONT,T1.FACT_DAEM 
order by T1.SEFA_CODI,T1.fact_CODI
